# Generated by Django 4.1.2 on 2022-10-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='year_of_release',
            new_name='release_year',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='title',
        ),
    ]
