# Generated by Django 4.1.2 on 2022-11-03 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_rename_year_of_release_album_release_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
    ]
